### ISSUE TITLE
AttributeError: 'int' object has no attribute 'isnumeric'

### ISSUE THREAD

**Issue by brianmay** [crucialfelix/django-ajax-selects#117]
Hello,

If the value to _as_pk is already int, _as_pk fails:

```
Traceback (most recent call last):
  File "/home/brian/tree/django/karaage/karaage/karaage/tests/machines/test_forms.py", line 49, in test_valid_data
    self.assertEqual(form.is_valid(), True, form.errors.items())
  File "/usr/lib/python3/dist-packages/django/forms/forms.py", line 162, in is_valid
    return self.is_bound and not bool(self.errors)
  File "/usr/lib/python3/dist-packages/django/forms/forms.py", line 154, in errors
    self.full_clean()
  File "/usr/lib/python3/dist-packages/django/forms/forms.py", line 353, in full_clean
    self._clean_fields()
  File "/usr/lib/python3/dist-packages/django/forms/forms.py", line 362, in _clean_fields
    value = field.widget.value_from_datadict(self.data, self.files, self.add_prefix(name))
  File "/usr/lib/python3/dist-packages/ajax_select/fields.py", line 111, in value_from_datadict
    return _as_pk(data.get(name, None))
  File "/usr/lib/python3/dist-packages/ajax_select/fields.py", line 29, in _as_pk
    if got.isnumeric():
AttributeError: 'int' object has no attribute 'isnumeric'
```

**Comment by brianmay** [comment]
I suggest something like the following patch to fix this:

```diff
Index: django-ajax-selects/ajax_select/fields.py
===================================================================
--- django-ajax-selects.orig/ajax_select/fields.py      2015-04-07 01:41:13.000000000 +1000
+++ django-ajax-selects/ajax_select/fields.py   2015-04-10 13:19:52.290799463 +1000
@@ -26,6 +26,10 @@
 
 def _as_pk(got):
     # a unicode method that checks for integers
+    if isinstance(got, int):
+        return got
+    if IS_PYTHON2 and isinstance(got, long):
+        return got
     if got.isnumeric():
         if IS_PYTHON2:
             return long(got)
```

**Comment by crucialfelix** [comment]
isnumeric is a method of Unicode. So we should check that first.

I've gotten unit tests and Travis, Tox set up so soon these pull requests
can be vetted a lot easier. With all the Django versions and python
versions it's become difficult to maintain.

**Comment by crucialfelix** [comment]
basic travis and tox are now added. I will implement tests when I get a
chance.

I think that maybe your test (the one that showed this error) is supplying
an int, but coming in from the request it is always a unicode.

in any case the correct way is to get the model field and use its
topython()

https://docs.djangoproject.com/en/1.8/howto/custom-model-fields/#converting-values-to-python-objects

but I don't see any reason why the form field or widget should be doing
this anyway. it was sent as a pull request and I maybe should not have
accepted it.

**Comment by brianmay** [comment]
Thanks for your prompt fix.

Yes, I was wondering about my code too. I couldn't see the problem yesterday. Oh wait, I see the issue now, will fix it.

**Comment by gwenau** [comment]
isnumeric() works in Python 3. It does not seem to work in Python2.

**Comment by crucialfelix** [comment]
It's a method of unicode, but not of str:

```python
>>> u"2".isnumeric()
True
>>> "2".isnumeric()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'str' object has no attribute 'isnumeric'
```
