### ISSUE TITLE
Working with ModelCluster's ParentalManyToManyField (Wagtail CMS)

### ISSUE THREAD

**Issue by jpbullalayao** [crucialfelix/django-ajax-selects#209]
Hello everybody,

I'm not sure if this is supposed to go into the Wagtail Issues or these issues, but regardless I'm looking for somebody that may have worked with both django-ajax-selects/Wagtail and can point me in the right direction to find the solution to my problem. I'm trying to use django-ajax-selects to have a M2M Selector/Creator widget in the Wagtail CMS for one of my `ParentalManyToManyField`s in my DB. 

I have the following code snippets:

blog_articles/models.py
```python
class BlogArticle(BasePage):
  ...
  categories = ParentalManyToManyField(Category, related_name='blog_articles', blank=True)
  ...
  content_panels = [
    MultiFieldPanel(
        [
          FieldPanel('categories')
        ]
    ) 
  ]
  ...
  base_form_class = BlogArticleForm
```

blog_articles/forms.py
```python
class BlogArticleForm(WagtailAdminPageForm):
 categories = AutoCompleteSelectMultipleField('categories', required=False)
```

wagtail_hooks.py (for checking the `add` button permission):
```python
@hooks.register('before_edit_page')
def check_add_permission(request, parent_page):
  autoselect_fields_check_can_add(BlogArticleForm, parent_page, request.user)
```

So, the problem is that when I click Save Draft/Publish on an edit page in the Wagtail CMS, I get the following error: 

```
AttributeError: 'unicode' object has no attribute 'pk'
```

The interesting thing is that if I had `models.ManyToMany` field instead of Wagtail/modelcluster's `ParentalManyToManyField`, I am able to successfully Save/Publish my article. So it seems to be a matter of getting django-ajax-selects and Wagtail working seamlessly together.

Does anyone have any pointers on this?

**Comment by crucialfelix** [comment]
That would be something in their ParentalManyToManyField calling `.pk`.  Can you link to their cms ? I've never heard of it.

**Comment by jpbullalayao** [comment]
@crucialfelix Hello!

This would be a major help if you're able to help me figure out what I may need to do especially considering that I'm still learning Python/Django

Here is Modelcluster: https://github.com/wagtail/django-modelcluster/blob/master/modelcluster/models.py

If you look at line 211, the method `serializable_data` does `obj[field.name] = [child.pk for child in children]` on line 225. If you need a whole stack trace to see the entire chain of function calls happening, I will gladly provide one!

For `children,` the value I should be getting should be something like:

```
[<Category: Category A>, <Category: Category M>]
```

Each object in this array would have a `pk`
 
But instead, I'm getting an array of IDs somehow:
```
[u'1', u'13’]
```

Thanks!

**Comment by jpbullalayao** [comment]
I will just provide a stacktrace anyways in case it's helpful:

```
DjangoLogger :: 2017-08-04 19:58:41  [INFO] :: name=werkzeug func=_log lineno=87 session_key= :: 127.0.0.1 - - [04/Aug/2017 19:58:41] "POST /cms/pages/5333/edit/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/jourdan/.virtualenvs/wagcontent/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/Users/jourdan/.virtualenvs/wagcontent/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 157, in __call__
    response = self.get_response(request)
  File "/Users/jourdan/.virtualenvs/wagcontent/lib/python2.7/site-packages/django/core/handlers/base.py", line 124, in get_response
    response = self._middleware_chain(request)
  File "/Users/jourdan/.virtualenvs/wagcontent/lib/python2.7/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/Users/jourdan/.virtualenvs/wagcontent/lib/python2.7/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/Users/jourdan/.virtualenvs/wagcontent/lib/python2.7/site-packages/django/core/handlers/exception.py", line 139, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/Users/jourdan/.virtualenvs/wagcontent/lib/python2.7/site-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/Users/jourdan/.virtualenvs/wagcontent/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/jourdan/.virtualenvs/wagcontent/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/Users/jourdan/.virtualenvs/wagcontent/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/jourdan/.virtualenvs/wagcontent/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jourdan/.virtualenvs/wagcontent/lib/python2.7/site-packages/django/views/decorators/cache.py", line 43, in _cache_controlled
    response = viewfunc(request, *args, **kw)
  File "/Users/jourdan/.virtualenvs/wagcontent/lib/python2.7/site-packages/wagtail/wagtailadmin/decorators.py", line 27, in decorated_view
    return view_func(request, *args, **kwargs)
  File "/Users/jourdan/.virtualenvs/wagcontent/lib/python2.7/site-packages/wagtail/wagtailadmin/views/pages.py", line 346, in edit
    submitted_for_moderation=is_submitting,
  File "/Users/jourdan/.virtualenvs/wagcontent/lib/python2.7/site-packages/wagtail/wagtailcore/models.py", line 640, in save_revision
    content_json=self.to_json(),
  File "/Users/jourdan/.virtualenvs/wagcontent/lib/python2.7/site-packages/modelcluster/models.py", line 230, in to_json
    return json.dumps(self.serializable_data(), cls=DjangoJSONEncoder)
  File "/Users/jourdan/.virtualenvs/wagcontent/lib/python2.7/site-packages/modelcluster/models.py", line 225, in serializable_data
    obj[field.name] = [child.pk for child in children]
AttributeError: 'unicode' object has no attribute 'pk'
```

**Comment by crucialfelix** [comment]
They shouldn't be doing this:

`    obj[field.name] = [child.pk for child in children] `

Just do

`    obj[field.name] = children `

The Django ORM will accept a list of objects or a list of primary keys.
