### ISSUE TITLE
It only can work for admin user

### ISSUE THREAD

**Issue by zhaowei699** [crucialfelix/django-ajax-selects#264]
I create Form liking this by forms.ModelForm:
`widgets = {
            'project': AutoCompleteSelectWidget('projects','Enter project name or code to filter'),
        }`
If I use admin user to log in, its performance is good.
But if I use a not admin user to log in, its performance liking a general text input and it can't filter.

I don't know the reason? welcome to any suggestion.

**Comment by zhaowei699** [comment]
Forbidden (Permission denied): /ajax_select/ajax_lookup/projects
Traceback (most recent call last):
  File "C:\my_env_python\django\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\my_env_python\django\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\my_env_python\django\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\my_env_python\django\lib\site-packages\ajax_select\views.py", line 33, in ajax_lookup
    lookup.check_auth(request)
  File "C:\my_env_python\django\lib\site-packages\ajax_select\lookup_channel.py", line 145, in check_auth
    raise PermissionDenied
django.core.exceptions.PermissionDenied
[23/Apr/2020 15:56:05] "GET /ajax_select/ajax_lookup/projects?term=6 HTTP/1.1" 403 22

How to use at the outside of admin?

**Comment by zhaowei699** [comment]
overwrite:
`def check_auth(self, request):`
can solve.

**Comment by crucialfelix** [comment]
See also: https://django-ajax-selects.readthedocs.io/en/latest/Outside-of-Admin.html if you want to place just a form on a public page.  The documentation is not so good there, sorry.

**Comment by zhaowei699** [comment]
Thanks crucialfelix.
This module and document are very usefull for us.
Thanks for your good job again.
